=== camilothorne/rest-WSD/results/annotations.dtd
<!ELEMENT Annotation (MedlineCitation+)>
<!ELEMENT MedlineCitation (Sentence+)>
<!ATTLIST MedlineCitation pmid CDATA #REQUIRED>

<!ELEMENT Sentence (Predications*)>
<!ATTLIST Sentence 
	  section (abstract|title)  #REQUIRED
          number CDATA #REQUIRED
          text CDATA #REQUIRED
>

<!ELEMENT Predications (Predication+)>
<!ELEMENT Predication (Predicate,Subject,Object)>
<!ELEMENT Predicate EMPTY>
<!ELEMENT Subject
	  (CUI?,PreferredName?,SemanticTypes,RelationSemanticType,
	  EntrezGene?)>
<!ELEMENT Object
	  (CUI?,PreferredName?,SemanticTypes,RelationSemanticType,
	  EntrezGene?)>

<!ATTLIST Predication 
	  negated (true | false) "false"
	  inferred (true | false) "false"
>
<!ATTLIST Predicate 
	  type ( ADMINISTERED_TO | AFFECTS | ASSOCIATED_WITH |
	          AUGMENTS | CAUSES | COEXISTS_WITH | CONVERTS_TO |
	          COMPLICATES | DIAGNOSES | DISRUPTS | INHIBITS |
	          INTERACTS_WITH | ISA | LOCATION_OF | MANIFESTATION_OF | 
	          METHOD_OF | OCCURS_IN | PART_OF | PRECEDES|
	          PREDISPOSES | PREVENTS | PROCESS_OF | PRODUCES | 
	          STIMULATES | TREATS | USES | 
	          COMPARED_WITH | HIGHER_THAN | LOWER_THAN | SAME_AS
	  ) #REQUIRED
	  indicatorType ( VERB | NOM |  ADJ | MOD_HEAD | PREP | 
	                          AUX | PART | SPEC | INFER | COMPLEX
	  ) #REQUIRED
	  charOffset CDATA ""
	  text CDATA ""
>
<!ATTLIST Subject 
	  charOffset CDATA  ""
	  text CDATA ""
>
<!ATTLIST Object 
	  charOffset CDATA  ""
	  text CDATA ""
>

<!ELEMENT CUI (#PCDATA)>
<!ELEMENT PreferredName (#PCDATA)>
<!ELEMENT SemanticTypes (SemanticType+)>
<!ELEMENT SemanticType (#PCDATA)>
<!ELEMENT RelationSemanticType (#PCDATA)>
<!ELEMENT EntrezGene (EntrezGeneTerm+)>
<!ELEMENT EntrezGeneTerm EMPTY>
<!ATTLIST EntrezGeneTerm
	  id CDATA #REQUIRED
	  name CDATA #REQUIRED
>

=== camilothorne/rest-WSD/results/adjudicated-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Annotation SYSTEM "annotations.dtd">
<Annotation>
  <MedlineCitation pmid="12368048">
    <Sentence section="title" number="1" text="Strategies for preclinical evaluation of dendritic cell subsets for promotion of transplant tolerance in the nonhuman primate.">
      <Predications>
        <Predication negated="false" inferred="false">
          <Predicate type="PROCESS_OF" indicatorType="PREP" charOffset="101" text="in" />
          <Subject charOffset="81" text="transplant tolerance">
            <CUI>C0887936</CUI>
            <PreferredName>Transplantation Tolerance</PreferredName>
            <SemanticTypes>
              <SemanticType>Organism Function</SemanticType>
            </SemanticTypes>
            <RelationSemanticType>Organism Function</RelationSemanticType>
          </Subject>
          <Object charOffset="109" text="nonhuman primate">
            <CUI>C0237798</CUI>
            <PreferredName>Nonhuman Primates</PreferredName>
            <SemanticTypes>
              <SemanticType>Mammal</SemanticType>
            </SemanticTypes>
            <RelationSemanticType>Mammal</RelationSemanticType>
          </Object>
        </Predication>
      </Predications>
    </Sentence>
  </MedlineCitation>
  <MedlineCitation pmid="12641497">
    <Sentence section="abstract" number="1" text="AIM: To perform a systematic review of the efficacy of rabeprazole-based therapies in Helicobacter pylori eradication, and to conduct a meta-analysis comparing the efficacy of rabeprazole and other proton pump inhibitors when co-prescribed with antibiotics.">
      <Predications>
        <Predication negated="false" inferred="false">
          <Predicate type="COMPARED_WITH" indicatorType="VERB" charOffset="150" text="comparing" />
          <Subject charOffset="198" text="proton pump inhibitors">
            <CUI>C0358591</CUI>
            <PreferredName>Proton Pump Inhibitors</PreferredName>
            <SemanticTypes>
              <SemanticType>Pharmacologic Substance</SemanticType>
            </SemanticTypes>
            <RelationSemanticType>Pharmacologic Substance</RelationSemanticType>
          </Subject>
          <Object charOffset="176" text="rabeprazole">
            <CUI>C0378482</CUI>
            <PreferredName>rabeprazole</PreferredName>
            <SemanticTypes>
              <SemanticType>Organic Chemical</SemanticType>
              <SemanticType>Pharmacologic Substance</SemanticType>
            </SemanticTypes>
            <RelationSemanticType>Pharmacologic Substance</RelationSemanticType>
          </Object>
        </Predication>
        <Predication negated="false" inferred="false">
          <Predicate type="USES" indicatorType="MOD_HEAD" charOffset="" text="" />
          <Subject charOffset="73" text="therapies">
            <CUI>C0087111</CUI>
            <PreferredName>Therapeutic procedure</PreferredName>
            <SemanticTypes>
              <SemanticType>Therapeutic or Preventive Procedure</SemanticType>
            </SemanticTypes>
            <RelationSemanticType>Therapeutic or Preventive Procedure</RelationSemanticType>
          </Subject>
          <Object charOffset="55" text="rabeprazole">
            <CUI>C0378482</CUI>
            <PreferredName>rabeprazole</PreferredName>
            <SemanticTypes>
              <SemanticType>Organic Chemical</SemanticType>
              <SemanticType>Pharmacologic Substance</SemanticType>
            </SemanticTypes>
            <RelationSemanticType>Pharmacologic Substance</RelationSemanticType>
          </Object>
        </Predication>
      </Predications>
    </Sentence>
  </MedlineCitation>
</Annotation>
